packages:
  - "packages/*"
  - "demo"

catalog:
  ziko: '^2.0.0-beta.8'

minimumReleaseAgeExclude:
  - ziko@2.0.0-beta.8
  - '@zikojs/express@0.1.1'
  - '@zikojs/http@0.1.1'
  - '@zikojs/server@0.6.0'
